export const productArray = [
    {
      name: "RAINYDAYS RAIN JACET",
      id: 1,
      size: "One Size",
      color: "gry",
      catagory: "Women",
      price: 150,
      image : "../images/item-1.jpg",
      Url: "item1.html",
    },
    {
      name: "RAINYDAYS RAIN JACET",
      id: 1,
      size: "One Size",
      color: "gry",
      catagory: "Women",
      price: 150,
      image : "../images/item-1.jpg",
      Url: "item1.html",
    },
    {
      name: "RAINYDAYS RAIN JACET",
      id: 1,
      size: "One Size",
      color: "gry",
      catagory: "Women",
      price: 150,
      image : "../images/item-1.jpg",
      Url: "item1.html",
    },
    {
      name: "RAINYDAYS RAIN JACET",
      id: 1,
      size: "One Size",
      color: "gry",
      catagory: "Women",
      price: 150,
      image : "../images/item-1.jpg",
      
      Url: "item1.html",
    },
    {
      name: "RAINYDAYS RAIN JACET",
      id: 1,
      size: "One Size",
      color: "gry",
      catagory: "Women",
      price: 150,
      image : "../images/item-1.jpg",
      Url: "item1.html",
    },
    {
      name: "RAINYDAYS RAIN JACET",
      id: 1,
      size: "One Size",
      color: "gry",
      catagory: "Women",
      price: 150,
      image : "../images/item-1.jpg",
      Url: "item1.html",
    }, 
  ];
  