export const menProductList = [
  {
    name: "RAINYDAYS RAIN JACET",
    id: 1,
    size: "One Size",
    color: "Navi",
    catagory: "Men",
    price: 200,
    image: "../images/item-3.jpeg",
    itemNumber: "#333333",
    Url: "https://elated-kepler-1f7dec.netlify.app/item3.html",
  },
  {
    name: "RAINYDAYS RAIN JACET",
    id: 1,
    size: "One Size",
    color: "Navi",
    catagory: "Men",
    price: 200,
    image: "../images/item-3.jpeg",
    itemNumber: "#333333",
    Url: "https://elated-kepler-1f7dec.netlify.app/item3.html",
  },
  {
    name: "RAINYDAYS RAIN JACET",
    id: 1,
    size: "One Size",
    color: "Navi",
    catagory: "Men",
    price: 200,
    image: "../images/item-3.jpeg",
    itemNumber: "#333333",
    Url: "https://elated-kepler-1f7dec.netlify.app/item3.html",
  },
  {
    name: "RAINYDAYS RAIN JACET",
    id: 1,
    size: "One Size",
    color: "Navi",
    catagory: "Men",
    price: 200,
    image: "../images/item-3.jpeg",
    itemNumber: "#333333",
    Url: "https://elated-kepler-1f7dec.netlify.app/item3.html",
  },
  {
    name: "RAINYDAYS RAIN JACET",
    id: 1,
    size: "One Size",
    color: "Navi",
    catagory: "Men",
    price: 200,
    image: "../images/item-3.jpeg",
    itemNumber: "#333333",
    Url: "https://elated-kepler-1f7dec.netlify.app/item3.html",
  },
  {
    name: "RAINYDAYS RAIN JACET",
    id: 1,
    size: "One Size",
    color: "Navi",
    catagory: "Men",
    price: 200,
    image: "../images/item-3.jpeg",
    itemNumber: "#333333",
    Url: "https://elated-kepler-1f7dec.netlify.app/item3.html",
  },
];
