export const saleProductList = [
  
    {
        name: "RAINYDAYS RAIN JACET",
        id: 3,
        size: "One Size",
        color: "Green",
        catagory: "Women",
        price: 99,
        oldPrice: "300",
        image : "../images/item-4.jpg",
        Url: "item4.html",
      },{
        name: "RAINYDAYS RAIN JACET",
        id: 3,
        size: "One Size",
        color: "Green",
        catagory: "Women",
        price: 99,
        oldPrice: "300",
        image : "../images/item-4.jpg",
        Url: "item4.html",
      },{
        name: "RAINYDAYS RAIN JACET",
        id:3,
        size: "One Size",
        color: "Green",
        catagory: "Women",
        price: 99,
        oldPrice: "300",
        image : "../images/item-4.jpg",
        Url: "item4.html",
      },{
        name: "RAINYDAYS RAIN JACET",
        id: 3,
        size: "One Size",
        color: "Green",
        catagory: "Women",
        price: 99,
        oldPrice: "300",
        image : "../images/item-4.jpg",
        Url: "item4.html",
      },{
        name: "RAINYDAYS RAIN JACET",
        id: 3,
        size: "One Size",
        color: "Green",
        catagory: "Women",
        price: 99,
        oldPrice: "300",
        image : "../images/item-4.jpg",
        Url: "item4.html",
      },{
        name: "RAINYDAYS RAIN JACET",
        id: 3,
        size: "One Size",
        color: "Green",
        catagory: "Women",
        price: 99,
        oldPrice: "300",
        image : "../images/item-4.jpg",
        Url: "item4.html",
      },
  ];
  