export const womenProductList = [
  
    {
        name: "RAINYDAYS RAIN JACET",
        id: 2,
        size: "One Size",
        color: "Green",
        catagory: "Women",
        price: 220,
        image : "../images/item-2.jpeg",
        Url: "https://elated-kepler-1f7dec.netlify.app/item2.html",
      },{
        name: "RAINYDAYS RAIN JACET",
        id: 2,
        size: "One Size",
        color: "Green",
        catagory: "Women",
        price: 220,
        image : "../images/item-2.jpeg",
        Url: "https://elated-kepler-1f7dec.netlify.app/item2.html",
      },{
        name: "RAINYDAYS RAIN JACET",
        id:2,
        size: "One Size",
        color: "Green",
        catagory: "Women",
        price: 220,
        image : "../images/item-2.jpeg",
        Url: "https://elated-kepler-1f7dec.netlify.app/item2.html",
      },{
        name: "RAINYDAYS RAIN JACET",
        id: 2,
        size: "One Size",
        color: "Green",
        catagory: "Women",
        price: 220,
        image : "../images/item-2.jpeg",
        Url: "https://elated-kepler-1f7dec.netlify.app/item2.html",
      },{
        name: "RAINYDAYS RAIN JACET",
        id: 2,
        size: "One Size",
        color: "Green",
        catagory: "Women",
        price: 220,
        image : "../images/item-2.jpeg",
        Url: "https://elated-kepler-1f7dec.netlify.app/item2.html",
      },{
        name: "RAINYDAYS RAIN JACET",
        id: 2,
        size: "One Size",
        color: "Green",
        catagory: "Women",
        price: 220,
        image : "../images/item-2.jpeg",
        Url: "https://elated-kepler-1f7dec.netlify.app/item2.html",
      },
  ];
  